export default new Set([
  "ssl.google-analytics.com",
  "www.google-analytics.com",
  "ads.google.com",
  "adservice.google.com",
  "ampcid.google.com",
  "fundingchoices.google.com",
  "crashlytics2.l.google.com",
  "pagead-googlehosted.l.google.com",
  "s0-2mdn-net.l.google.com",
  "www-googletagmanager.l.google.com",
  "video-stats.video.google.com",
  "www.googletagmanager.com",
  "googletagmanager.com",
]);
