export const routes = {
  blog: "/blog",
  confirmEmail: "/confirm-email",
  docs: "/docs",
  gitHub: "/github",
  gitHubIntegration: "/github-integration",
  home: "/",
  invite: "/invite",
  logIn: "/log-in",
  notFound: "/404",
  playground: "/playground",
  pricing: "/pricing",
  run: "/run",
  settings: "/settings",
  signUp: "/sign-up",
  slack: "/slack",
  suites: "/suites",
  test: "/test",
  tests: "/tests",
};
