export const routes = {
  blog: "/blog",
  checkout: "/checkout",
  checkoutSuccess: "/checkout-success",
  confirmEmail: "/confirm-email",
  docs: "/docs",
  getStarted: "/get-started",
  gitHub: "/github",
  gitHubIntegration: "/github-integration",
  guides: "/guides",
  home: "/",
  invite: "/invite",
  logIn: "/log-in",
  notFound: "/404",
  pricing: "/pricing",
  run: "/run",
  settings: "/settings",
  signUp: "/sign-up",
  slack: "/slack",
  suites: "/suites",
  test: "/test",
  tests: "/tests",
};
