export const routes = {
  blog: "/blog",
  confirmEmail: "/confirm-email",
  create: "/test",
  docs: "/docs",
  gitHub: "/github",
  home: "/",
  invite: "/invite",
  logIn: "/log-in",
  notFound: "/404",
  pricing: "/pricing",
  run: "/run",
  signUp: "/sign-up",
  slack: "/slack",
  test: "/test",
  tests: "/tests",
};
