name: qawolf
on:
  push:
    # test every branch
    # edit below if you only want certain branches tested
    branches: "*"
  # schedule:
  #   # test on schedule using cron syntax
  #   - cron: "0 * * * *" # every hour
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: qawolf test
        uses: qawolf/qawolf@master
        # env:
        #   # configure tests with environment variables
        #   # set "QAW_URL" to override the url for all tests
        #   QAW_URL: www.my_staging_url.com
        #   # set "QAW_TESTNAME_URL" to override the url for the test named "testname"
        #   QAW_CREATE_ACCOUNT_URL: www.mysite.com/createaccount
        #   # set "QAW_TESTNAME_0" to override values[0] for the test named "testname"
        #   QAW_LOGIN_0: "my_username"
        #   # you can also use GitHub secrets for environment variables
        #   # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
        #   QAW_LOGIN_1: ${{ secrets.PASSWORD }}
      - name: Upload Artifacts
        # include test artifacts
        # edit below to only include artifacts in certain scenarios
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: qawolf
          path: "./artifacts"
    ## use your container in the workflow
    # services:
    #   my_service:
    #     image: owner/image:tag
